package com.common.commoncapcha.generate;

import cn.hutool.core.util.RandomUtil;
import cn.hutool.core.util.StrUtil;


/**
 * Random code will be generated by this class after CaptchaManage compile
 */
public class RandomGenerator extends CodeGeneratorManage{

    public RandomGenerator(int count){
        super(count);
    }

    @Override
    public String generateCaptcha() {
        return RandomUtil.randomString(this.baseStr, this.length);
    }

    @Override
    public boolean verifyCaptcha(String defaultCode, String userInputCode) {
        if (StrUtil.isNotBlank(userInputCode)){
            return StrUtil.equals(defaultCode, userInputCode);
        }
        return false;
    }

}
